### ISSUE TITLE
Detection After Beacon Button Press

### ISSUE THREAD

**Issue by hartmch** [lasarobotics/FTCVision#102]
First thank you for this library.  Our team based our opmode off of the LinearVisionSample provided.  Everything is mostly working great and I may be missing something but is it possible to detect if the beacon is all red or all blue after a button press to verify the right button was pressed?  Currently I still get either red/blue or blue/red even when it is a solid color.

Thanks for your help.

Chad Hartman
Team 9087

**Comment by smo-key** [comment]
@hartmch **TL;DR Not without modification or some creativity on your part.**

All three algorithms (FAST, COMPLEX, and REALTIME) are optimized to detect only red/blue, blue/red, or nonexistent. An older version of the COMPLEX algorithm detected any possible state, but took about twice as long per frame and was less accurate. Teams surveyed last season did not have a need to detect when both colors were the same so the functionality was left out.

However, this is possible if you wish to modify the FAST or REALTIME algorithms. I can help you do this if absolutely necessary. 

**You can also simply back up a bit and check the confidence rating** - if the rating is very low and you are in the same position, then the beacon is either not in frame or both colors have lit.

Let me know if you need any further help.
Arthur Pachachura (smo-key)

**Comment by hartmch** [comment]
Thank you for the information.  I think we are going to redesign are button pushing mechanism to help with the accuracy.  Thanks for your help.
