### ISSUE TITLE
RuntimeException when using LinearVisionSample

### ISSUE THREAD

**Issue by IanBurwell** [lasarobotics/FTCVision#104]
When using LinearVisionSample with the latest version of the sdk we get an error that reads, " Error: User code threw an uncaught exception: RuntimeException - Can't create handler inside thread that has not called Looper.prepare();"

**Comment by smo-key** [comment]
Hi SpyGuylan,

Can you use Android Studio to paste the entire exception (should have line
numbers in it)?

smo-key

**Comment by IanBurwell** [comment]
Sorry guys! After installing open CV manager it worked like a dream!
