### ISSUE TITLE
Clean out old branches

### ISSUE THREAD

**Issue by qwertychouskie** [lasarobotics/FTCVision#106]
There are some old branches that should be deleted, e.g. `feature-distance`, `feature-distance2`, and `feature-distance3`, which were replaced by `feature-distance5`.

**Comment by ehsanmasdar** [comment]
@qwertychouskie Agreed. @smo-key can you confirm that there is nothing useful on those branches. We have a bunch of feature branches that given their age/lack of activity should have either all been merged or deleted at this point.

**Comment by smo-key** [comment]
Hey @qwertychouskie, I cleaned out all of the stale branches with except QR code detection.
