### ISSUE TITLE
Cascade Training

### ISSUE THREAD

**Issue by WSlatton** [lasarobotics/FTCVision#17]
Training the HAAR cascades is a much more involved process than I had previously anticipated. Generating the classifier with only 10 positive and 20 negative samples is taking around twenty minutes for only four stages on my machine. Using cascade is certainly still an option, but it's going to take a while to get a decent classifier working. If anyone has a more powerful machine, which could be brought in or that we could remotely access to train these, leave a comment below.

**Comment by smo-key** [comment]
@WSlatton What are your machine specs? If mine are significantly greater, I can bring in a machine or set up remote access.

**Comment by WSlatton** [comment]
Quad-core 2.3 GHz, 4 GB RAM, Intel HD 3000 integrated graphics. I can still train it on my machine, but a high-quality one is going to take forever.

**Comment by smo-key** [comment]
@WSlatton High quality? Lower the quality as much as possible and see if it works!

Can you provide me with your test image suite?

**Comment by smo-key** [comment]
Moved to new repository to save space.
