### ISSUE TITLE
Disabling Checking

### ISSUE THREAD

**Issue by WSlatton** [lasarobotics/FTCVision#22]
@smo-key are you able to disable status checking? Travis CI appears to be down, and it's preventing any PRs.

**Comment by ehsanmasdar** [comment]
@WSlatton @smo-key  Travis CI seems to be up and has not had any issues today (status.travis-ci.com). Maybe issue on the school network? Even if it was down, it's probably not a good idea to disable it because that could allow potentially unstable code into a pre release/release branch.

**Comment by ehsanmasdar** [comment]
@WSlatton @smo-key Ah, I see the problem. Deleting the .travis.yml file won't stop Travis CI from working, it just won't report status properly. This is probably the issue you are seeing with your pull request.

**Comment by WSlatton** [comment]
It was failing before I deleted that. I did so in an attempt to temporarily disable it, as travis-ci.org was down. It looks like everything's back up now, though.

**Comment by smo-key** [comment]
@Oksisane @WSlatton From now on, Travis will only build if the `.travis.yml` file is present. If it is not, merges will never succeed.
