### ISSUE TITLE
Can an admin re-enable Homu?

### ISSUE THREAD

**Issue by WSlatton** [lasarobotics/FTCVision#23]
It appears that I may have inadvertently disabled Homu on this repository while trying to find the source of the problems with the status checking (the Travis-CI backend was just down, everything's fine now). For some reason I was able to do that, but seen unable to re-enable it. Could someone with administrative rights do so? Sorry about that.

**Comment by smo-key** [comment]
@WSlatton Re-enabled... please file a PR to test.

**Comment by smo-key** [comment]
@WSlatton Fixed. Closing #23.
