### ISSUE TITLE
Travis-CI down again

### ISSUE THREAD

**Issue by WSlatton** [lasarobotics/FTCVision#25]
Travis-CI appears to be offline again. Their backend seems to be highly unstable at the moment, maybe we should disable it until this has been fixed.

![capture](https://cloud.githubusercontent.com/assets/7821178/10819329/69405b8a-7e15-11e5-81f5-9a5b261581c6.PNG)

**Comment by smo-key** [comment]
It may just be the school WiFi. Travis CI reports normal functionality.

Remember, you can still create pull requests if you can't view the build
results online.

**Comment by WSlatton** [comment]
It's back up for me too, but there was definitely a problem earlier. The status report has been hanging for a while on one of the PRs (it just passed a few minutes ago), so I don't think that the issue was only on my end. Travis-CI reported outages a few days ago due to a supposed DDOS attack, so that may be the issue again. Hopefully it'll stay up from now on though.

**Comment by smo-key** [comment]
Yes, Travis has a few issues, but it prevents us from deploying or merging failed code, so as long as it works 99% of the time, we should keep it around.
