### ISSUE TITLE
Ellipse drawing with OpenCV 3.0.0

### ISSUE THREAD

**Issue by smo-key** [lasarobotics/FTCVision#37]
Well, here's our first OpenCV-related bug.

When drawing ellipses using `Imgproc.ellipse()`, weird things happen such as the ellipse color is incorrect or only part of the ellipse is drawn. Conclusion: `Imgproc.ellipse()` has a few bugs that OpenCV would take a while to correct. So we have a few options:

_Option 1: Revert to OpenCV 2.4.11_
So this option is safe, but we will lose the support to build OpenCV on any 64-bit phone (which means that ONLY the Moto G and the ZTE could be used for development. The chance that you have a 32-bit phone today is quite small.

_Option 2: Using JNI, write our own C++ code to fix the issue and require downloading our own APK from the Google Store to use Vision_
This option is pretty straightforward, but we will have to put in a lot of work to create the OpenCV Manager-like Play Store package that users can just download in addition to the OpenCV Manager.

_Option 3: Using JNI, require every user to build the additional fix code from scratch_
No. This is _severely_ complicated.

**Comment by willfisher** [comment]
My opinion is to go back to OpenCV 2.4

**Comment by ArnavMohan** [comment]
@willfisher I agree.

**Comment by russellsayshi** [comment]
I don't think this is necessary. OpenCV 3 is really good for us, and we
shouldn't abandon it so quickly. The colors are being inverted, and so
that's an easy fix. As for the partially drawn ellipses, that can be solved
some other way. I'll look into it today.

**Comment by smo-key** [comment]
@russellsayshi Okay, if you can solve the issue, then we can continue using 3.0.0. Otherwise, we will temporarily return to 2.4 for the 1.0 release and attempt option 2.
