### ISSUE TITLE
Screen-rotation correction

### ISSUE THREAD

**Issue by smo-key** [lasarobotics/FTCVision#38]
We should probably correct for screen rotation. Depending on what resolution camera you have, the screen orientation may need to be changed. Also, if you use an app to force an unlock of the screen rotation, then as you rotate the screen, the rotation of the drawn image should be correct. 

**Anyone want to help with this?**

**Comment by ArnavMohan** [comment]
@willfisher tomorrow i can finish this... unless you can today

**Comment by willfisher** [comment]
@ArnavMohan I have added to this, ill push it then you can work on it

**Comment by smo-key** [comment]
done, code currently in `dev` branch
