### ISSUE TITLE
IMPORTANT: Welcome to the FTC 2016-2017 Season!

### ISSUE THREAD

**Issue by smo-key** [lasarobotics/FTCVision#92]
_FTCVision_ will remain an **active library** for the new game, but we need YOUR help. Teams willing to learn how _FTCVision_ works and willing to help build the next version, let me know at pachachura.arthur@gmail.com or reply to this thread! As the founders of this library (@ehsanmasdar and myself) no longer have access to a game field, _it is up to a_ **_collective**_ _of teams to develop code specific to the new challenge_.

Teams wishing to use the library as-is for the 2016-2017 game that already have experience can use it immediately. Simply create a new `ManualVisionOpMode` tailored to your specific needs. As always, documentation is available at http://ftcvision.lasarobotics.org/ and examples present [here](https://github.com/lasarobotics/FTCVision/tree/master/ftc-robotcontroller/src/main/java/com/qualcomm/ftcrobotcontroller) and [here](https://github.com/lasarobotics/FTCVision/tree/master/ftc-cameratest/src/main/java/com/lasarobotics/tests/camera). The entirety of OpenCV is available to you so please learn about it [on their website](http://opencv.org/about.html)!

Good luck, teams!
@smo-key

**Comment by russellsayshi** [comment]
Yay new year! My team is interested in vision

**Comment by QuantumMango** [comment]
My team is interested in using vision. I haven't done much with CV, but I'm looking forward to it!

**Comment by EtherTyper** [comment]
@smo-key FTC 6504 Omegas is interested in the further use and development of your FTC Vision library.

**Comment by shaashwat** [comment]
Team 4096 T-10 used this library and will contribute to it. Is there anything to be done?

**Comment by freezone2000** [comment]
My team is interested in learning how the code really works. We've been going through various files such as BeaconAnalyzer and are currently attempting to make it detect if the beacon is fully lit. (isBeaconFullyLit() doesnt seem to work...)
