### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by Zero2848** [lasarobotics/FTCVision#95]
So recently I have seen an issue that many others have in the new SDK. Whenever an OpMode is initialized, the robot controller keeps crashing. However I think I found the issue, but dont exactly now why its causing an error. It seems to be in the telemetry in line 257 in https://github.com/lasarobotics/FTCVision/blob/master/ftc-visionlib/src/main/java/org/lasarobotics/vision/opmode/VisionOpModeCore.java#L257. Commenting this line out fixes the problem, but can anyone figure out why this occurs.

**Comment by buggy213** [comment]
Yep. I traced the problem back to JavaCameraView.java, in the class CameraWorker. From a brief glance, it looks like a threading issue.

**Comment by ehsanmasdar** [comment]
@buggy213 @Zero2848 If one of you could PR the fix I can get it committed into the library. Thanks for debugging this!

**Comment by ehsanmasdar** [comment]
@buggy213 @Zero2848 As far as you have seen, is the crash related only to the linked telemetry line and not other uses of the telemetry api in the library? The telemetry api is used quite a few times....

**Comment by buggy213** [comment]
Yes, it appears that it is just that line.

**Comment by buggy213** [comment]
Well this is awkward

**Comment by ehsanmasdar** [comment]
You deserve credit for it :)

**Comment by Zero2848** [comment]
Yeah its just this line. Everything else seems to work fine, however initinilization is sometime very slow(45-75 sec).

**Comment by qwertychouskie** [comment]
Related PRs merged, can be closed.
